// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu4b65sHn8smIBdcNf-WZgp0FtDuaZJnQ',
    appId: '1:1052068581654:web:5c83b19a11dcb4fde40037',
    messagingSenderId: '1052068581654',
    projectId: 'theremin-synth',
    authDomain: 'theremin-synth.firebaseapp.com',
    storageBucket: 'theremin-synth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrO1gmfCEXjjXwfARqqcbb7pOoVt1HYEM',
    appId: '1:1052068581654:android:e637acf3df211bfae40037',
    messagingSenderId: '1052068581654',
    projectId: 'theremin-synth',
    storageBucket: 'theremin-synth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxPo6RPv6wH_sUBafTHDULdUhkQrw5BwU',
    appId: '1:1052068581654:ios:50e643a7a3075e65e40037',
    messagingSenderId: '1052068581654',
    projectId: 'theremin-synth',
    storageBucket: 'theremin-synth.appspot.com',
    iosClientId:
        '1052068581654-6b14v7hah6pcna0obkqtaqd5mc4vupks.apps.googleusercontent.com',
    iosBundleId: 'com.example.thereminSynth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxPo6RPv6wH_sUBafTHDULdUhkQrw5BwU',
    appId: '1:1052068581654:ios:50e643a7a3075e65e40037',
    messagingSenderId: '1052068581654',
    projectId: 'theremin-synth',
    storageBucket: 'theremin-synth.appspot.com',
    iosClientId:
        '1052068581654-6b14v7hah6pcna0obkqtaqd5mc4vupks.apps.googleusercontent.com',
    iosBundleId: 'com.example.thereminSynth',
  );
}
